//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.28 at 08:56:09 PM EST 
//


package com.trireplicator.trainingpeaks;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Workout complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Workout">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="WorkoutId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="WorkoutDay" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="WorkoutTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PlannedDistanceInMeters" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="PlannedPace" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DistanceInMeters" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="PowerAverage" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="PowerMaximum" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="TimeTotalInSeconds" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="PlannedTimeTotalInSeconds" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="VelocityMaximum" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="VelocityAverage" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="CadenceMaximum" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="CadenceAverage" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="HeartRateMaximum" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="HeartRateMinimum" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="HeartRateAverage" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="StartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ElevationGain" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ElevationLoss" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ElevationMinimum" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ElevationMaximum" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ElevationAverage" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CoachComments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WorkoutCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StartTimePlanned" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Workout", propOrder = {
    "workoutId",
    "workoutDay",
    "workoutTypeDescription",
    "plannedDistanceInMeters",
    "plannedPace",
    "distanceInMeters",
    "powerAverage",
    "powerMaximum",
    "timeTotalInSeconds",
    "plannedTimeTotalInSeconds",
    "velocityMaximum",
    "velocityAverage",
    "cadenceMaximum",
    "cadenceAverage",
    "heartRateMaximum",
    "heartRateMinimum",
    "heartRateAverage",
    "startTime",
    "elevationGain",
    "elevationLoss",
    "elevationMinimum",
    "elevationMaximum",
    "elevationAverage",
    "description",
    "coachComments",
    "workoutCode",
    "title",
    "startTimePlanned"
})
public class Workout {

    @XmlElement(name = "WorkoutId")
    protected int workoutId;
    @XmlElement(name = "WorkoutDay", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar workoutDay;
    @XmlElement(name = "WorkoutTypeDescription")
    protected String workoutTypeDescription;
    @XmlElement(name = "PlannedDistanceInMeters", required = true, type = Double.class, nillable = true)
    protected Double plannedDistanceInMeters;
    @XmlElement(name = "PlannedPace")
    protected String plannedPace;
    @XmlElement(name = "DistanceInMeters", required = true, type = Double.class, nillable = true)
    protected Double distanceInMeters;
    @XmlElement(name = "PowerAverage", required = true, type = Short.class, nillable = true)
    protected Short powerAverage;
    @XmlElement(name = "PowerMaximum", required = true, type = Short.class, nillable = true)
    protected Short powerMaximum;
    @XmlElement(name = "TimeTotalInSeconds", required = true, type = Long.class, nillable = true)
    protected Long timeTotalInSeconds;
    @XmlElement(name = "PlannedTimeTotalInSeconds", required = true, type = Long.class, nillable = true)
    protected Long plannedTimeTotalInSeconds;
    @XmlElement(name = "VelocityMaximum", required = true, type = Double.class, nillable = true)
    protected Double velocityMaximum;
    @XmlElement(name = "VelocityAverage", required = true, type = Double.class, nillable = true)
    protected Double velocityAverage;
    @XmlElement(name = "CadenceMaximum", required = true, type = Integer.class, nillable = true)
    @XmlSchemaType(name = "unsignedShort")
    protected Integer cadenceMaximum;
    @XmlElement(name = "CadenceAverage", required = true, type = Integer.class, nillable = true)
    @XmlSchemaType(name = "unsignedShort")
    protected Integer cadenceAverage;
    @XmlElement(name = "HeartRateMaximum", required = true, type = Integer.class, nillable = true)
    @XmlSchemaType(name = "unsignedShort")
    protected Integer heartRateMaximum;
    @XmlElement(name = "HeartRateMinimum", required = true, type = Integer.class, nillable = true)
    @XmlSchemaType(name = "unsignedShort")
    protected Integer heartRateMinimum;
    @XmlElement(name = "HeartRateAverage", required = true, type = Integer.class, nillable = true)
    @XmlSchemaType(name = "unsignedShort")
    protected Integer heartRateAverage;
    @XmlElement(name = "StartTime", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlElement(name = "ElevationGain", required = true, type = Double.class, nillable = true)
    protected Double elevationGain;
    @XmlElement(name = "ElevationLoss", required = true, type = Double.class, nillable = true)
    protected Double elevationLoss;
    @XmlElement(name = "ElevationMinimum", required = true, type = Double.class, nillable = true)
    protected Double elevationMinimum;
    @XmlElement(name = "ElevationMaximum", required = true, type = Double.class, nillable = true)
    protected Double elevationMaximum;
    @XmlElement(name = "ElevationAverage", required = true, type = Double.class, nillable = true)
    protected Double elevationAverage;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "CoachComments")
    protected String coachComments;
    @XmlElement(name = "WorkoutCode")
    protected String workoutCode;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "StartTimePlanned", required = true, nillable = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTimePlanned;

    /**
     * Gets the value of the workoutId property.
     * 
     */
    public int getWorkoutId() {
        return workoutId;
    }

    /**
     * Sets the value of the workoutId property.
     * 
     */
    public void setWorkoutId(int value) {
        this.workoutId = value;
    }

    /**
     * Gets the value of the workoutDay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getWorkoutDay() {
        return workoutDay;
    }

    /**
     * Sets the value of the workoutDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setWorkoutDay(XMLGregorianCalendar value) {
        this.workoutDay = value;
    }

    /**
     * Gets the value of the workoutTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkoutTypeDescription() {
        return workoutTypeDescription;
    }

    /**
     * Sets the value of the workoutTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkoutTypeDescription(String value) {
        this.workoutTypeDescription = value;
    }

    /**
     * Gets the value of the plannedDistanceInMeters property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPlannedDistanceInMeters() {
        return plannedDistanceInMeters;
    }

    /**
     * Sets the value of the plannedDistanceInMeters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPlannedDistanceInMeters(Double value) {
        this.plannedDistanceInMeters = value;
    }

    /**
     * Gets the value of the plannedPace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlannedPace() {
        return plannedPace;
    }

    /**
     * Sets the value of the plannedPace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlannedPace(String value) {
        this.plannedPace = value;
    }

    /**
     * Gets the value of the distanceInMeters property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDistanceInMeters() {
        return distanceInMeters;
    }

    /**
     * Sets the value of the distanceInMeters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDistanceInMeters(Double value) {
        this.distanceInMeters = value;
    }

    /**
     * Gets the value of the powerAverage property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPowerAverage() {
        return powerAverage;
    }

    /**
     * Sets the value of the powerAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPowerAverage(Short value) {
        this.powerAverage = value;
    }

    /**
     * Gets the value of the powerMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getPowerMaximum() {
        return powerMaximum;
    }

    /**
     * Sets the value of the powerMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPowerMaximum(Short value) {
        this.powerMaximum = value;
    }

    /**
     * Gets the value of the timeTotalInSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTimeTotalInSeconds() {
        return timeTotalInSeconds;
    }

    /**
     * Sets the value of the timeTotalInSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTimeTotalInSeconds(Long value) {
        this.timeTotalInSeconds = value;
    }

    /**
     * Gets the value of the plannedTimeTotalInSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPlannedTimeTotalInSeconds() {
        return plannedTimeTotalInSeconds;
    }

    /**
     * Sets the value of the plannedTimeTotalInSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPlannedTimeTotalInSeconds(Long value) {
        this.plannedTimeTotalInSeconds = value;
    }

    /**
     * Gets the value of the velocityMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVelocityMaximum() {
        return velocityMaximum;
    }

    /**
     * Sets the value of the velocityMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVelocityMaximum(Double value) {
        this.velocityMaximum = value;
    }

    /**
     * Gets the value of the velocityAverage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getVelocityAverage() {
        return velocityAverage;
    }

    /**
     * Sets the value of the velocityAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setVelocityAverage(Double value) {
        this.velocityAverage = value;
    }

    /**
     * Gets the value of the cadenceMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCadenceMaximum() {
        return cadenceMaximum;
    }

    /**
     * Sets the value of the cadenceMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCadenceMaximum(Integer value) {
        this.cadenceMaximum = value;
    }

    /**
     * Gets the value of the cadenceAverage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCadenceAverage() {
        return cadenceAverage;
    }

    /**
     * Sets the value of the cadenceAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCadenceAverage(Integer value) {
        this.cadenceAverage = value;
    }

    /**
     * Gets the value of the heartRateMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHeartRateMaximum() {
        return heartRateMaximum;
    }

    /**
     * Sets the value of the heartRateMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeartRateMaximum(Integer value) {
        this.heartRateMaximum = value;
    }

    /**
     * Gets the value of the heartRateMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHeartRateMinimum() {
        return heartRateMinimum;
    }

    /**
     * Sets the value of the heartRateMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeartRateMinimum(Integer value) {
        this.heartRateMinimum = value;
    }

    /**
     * Gets the value of the heartRateAverage property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHeartRateAverage() {
        return heartRateAverage;
    }

    /**
     * Sets the value of the heartRateAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHeartRateAverage(Integer value) {
        this.heartRateAverage = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the elevationGain property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getElevationGain() {
        return elevationGain;
    }

    /**
     * Sets the value of the elevationGain property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setElevationGain(Double value) {
        this.elevationGain = value;
    }

    /**
     * Gets the value of the elevationLoss property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getElevationLoss() {
        return elevationLoss;
    }

    /**
     * Sets the value of the elevationLoss property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setElevationLoss(Double value) {
        this.elevationLoss = value;
    }

    /**
     * Gets the value of the elevationMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getElevationMinimum() {
        return elevationMinimum;
    }

    /**
     * Sets the value of the elevationMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setElevationMinimum(Double value) {
        this.elevationMinimum = value;
    }

    /**
     * Gets the value of the elevationMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getElevationMaximum() {
        return elevationMaximum;
    }

    /**
     * Sets the value of the elevationMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setElevationMaximum(Double value) {
        this.elevationMaximum = value;
    }

    /**
     * Gets the value of the elevationAverage property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getElevationAverage() {
        return elevationAverage;
    }

    /**
     * Sets the value of the elevationAverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setElevationAverage(Double value) {
        this.elevationAverage = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the coachComments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoachComments() {
        return coachComments;
    }

    /**
     * Sets the value of the coachComments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoachComments(String value) {
        this.coachComments = value;
    }

    /**
     * Gets the value of the workoutCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkoutCode() {
        return workoutCode;
    }

    /**
     * Sets the value of the workoutCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkoutCode(String value) {
        this.workoutCode = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the startTimePlanned property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTimePlanned() {
        return startTimePlanned;
    }

    /**
     * Sets the value of the startTimePlanned property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTimePlanned(XMLGregorianCalendar value) {
        this.startTimePlanned = value;
    }

}
